from src.constants.config import (
    MONGO_URI,
    MONGO_DB_NAME,
    MONGO_COLLECTION_NAME,
)
from src.constants.search import (
    CEDULA_CONTEXT_CHARS,
    CEDULA_LETTERS,
    CEDULA_DIGITS_MIN,
    CEDULA_DIGITS_MAX,
    SNIPPET_LEN_CEDULA,
)

__all__ = [
    "MONGO_URI",
    "MONGO_DB_NAME",
    "MONGO_COLLECTION_NAME",
    "CEDULA_CONTEXT_CHARS",
    "CEDULA_LETTERS",
    "CEDULA_DIGITS_MIN",
    "CEDULA_DIGITS_MAX",
    "SNIPPET_LEN_CEDULA",
]
